### ISSUE TITLE
Popular Articles widget/block from Jetpack using AMP-LIST

### ISSUE THREAD

**Issue by eduardogoncalves** [Automattic/newspack-theme#1023]
**Is your feature request related to a problem? Please describe.**
We need to rebuild cache many times a day, because Popular Articles' block become obsolete on post pages.

**Describe the solution you'd like**
As Newspack is AMP Canonical/AMP first, we could add a new block/widget that uses AMP-LIST to render a JSON with "Popular Articles" from Jetpack. So we can keep articles' page cached for more time, while Popular Articles' block keeps fresh but requesting fresh content from Jetpack.

![image](https://user-images.githubusercontent.com/4308648/90184487-2afe8900-dd83-11ea-80bd-a968418f086c.png)

**Comment by laurelfulford** [comment]
Apologies for the late reply! 

The theme itself doesn't have any blocks or widgets built into it, so I think this issue may be better suited for another repo -- I'm just not sure which.

If it's more to do with using AMP-LIST with Jetpack's top posts and pages, I would suggest the [Jetpack repo](https://github.com/automattic/jetpack). Jetpack isn't AMP-first, but they have been building in AMP support for different functionality. 

If it's more about building something fresh -- like a 'most visited' type block -- the [Newspack Blocks](https://github.com/automattic/newspack-blocks) repo could be best. [We have an older issue](https://github.com/Automattic/newspack-blocks/issues/49) that this could be added to, to add the ability to show the most popular articles in the Homepage Posts block, though it doesn't touch on using AMP-LIST at all at the moment.

I'm going to close this issue, since it's not specific to the theme, but please let me know if you have any questions!
