### ISSUE TITLE
Social icons are inconsistent

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#1081]
**Is your feature request related to a problem? Please describe.**
Depending on how/where they are inserted, social icons use different icons or styles.

On one site, for example, the social icons menu is given this treatment by the theme:

![Screenshot from 2020-09-21 15-52-37](https://user-images.githubusercontent.com/136342/93782649-bb51a880-fc22-11ea-9545-145bbe99cf58.png)

Then, in the slide-out menu, using the Jetpack social icons widget produces something slightly different (see Facebook):

![Screenshot from 2020-09-21 15-52-46](https://user-images.githubusercontent.com/136342/93782747-d6bcb380-fc22-11ea-81b3-db45e2ee74dc.png)

Then, when the social share icons are added to articles using Jetpack they are significantly different:

![Screenshot from 2020-09-21 15-52-58](https://user-images.githubusercontent.com/136342/93782815-e805c000-fc22-11ea-9240-f3e6e4f2a947.png)

**Describe the solution you'd like**
The style of social share icons should be consistent, whether provided by the theme or using Jetpack, regardless of how and where they are inserted. This helps with the constant visual reinforcement of the encouragement to share.

**Describe alternatives you've considered**
I guess the alternative is that styles are different, which seems like a design flaw? Thoughts welcome on that one!

**Comment by thomasguillot** [comment]
So I agree, there's a lack of consistency between our social menu and Jetpack social icons due to the fact our theme uses the old Facebook logo (updated to the new one here: #1082)

Now with the sharing icons I think it's a little bit different. To me the social + widget should blend in and match the theme whereas the sharing icons should be more "visible". So I wouldn't change the social share icons to match the menu.

**Comment by laurelfulford** [comment]
Thanks for updating the Facebook icon, @thomasguillot! 

> To me the social + widget should blend in and match the theme whereas the sharing icons should be more "visible". So I wouldn't change the social share icons to match the menu.

I totally agree with this! The icons themselves should definitely be consistent, but they might end up 'fighting' visually if they both look the same. It could also get confusing, since they serve different functions -- the menu social buttons are to encourage following the publisher's accounts, and the social share buttons encourage sharing individual stories. Having them look identical could muddy that a bit. 

Since the Facebook icon is updated, I'm going to close this one as 'wontfix-the-rest', but @philipjohn if you have any objection to this/would like to discuss it further, please reopen!

**Comment by philipjohn** [comment]
Thanks for looking and doing #1082 so quickly! Yeah, I see you're reasoning, and it makes sense to me.
