### ISSUE TITLE
Theme assumes $ makes sense as an icon for Sponsored Content

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#1085]
**Describe the bug**
When using the Sponsored Content flag, a $ sign is inserted into the label. This is fine for sites serving countries that have some sort of $ as their currency but not in a large number of countries thoughout Europe, Asia and the rest of the world. It looks like [the $ sign is hardcoded](https://github.com/Automattic/newspack-theme/blob/384b09b4128928256faccc162da80412cd8e2aa6/newspack-theme/classes/class-newspack-svg-icons.php#L187) with no option to change it based on locale.

**To Reproduce**
1. Enable the Sponsors plugin
1. Add a Sponsor
1. Create a post and assign it to the new sponsor
1. Publish the post and observe when viewed the "Sponsored" flag by the title, along with the $ sign 

**Screenshots**
![Screenshot from 2020-09-22 13-50-03](https://user-images.githubusercontent.com/136342/93884230-886aeb80-fcda-11ea-830c-04d6fa361a00.png)

**Expected behavior**
The symbol should match the default currency of the site (perhaps using WooCommerce settings) or not show at all.

**Comment by laurelfulford** [comment]
Urg, I can't believe I didn't consider that 🤦‍♀️ Especially since we have a number of publications already that don't use $. 

I'm leaning towards removing it all together -- it would be a less-complex solution ([look at all of these potential symbols](https://www.xe.com/symbols.php)!), and line up with how the blocks look (they don't have the icon, only the text). It would also fix an issue that's started driving me nuts: that `$` and `S` are just too similar looking to be sitting next to each other like that 😆

**Comment by philipjohn** [comment]
Thanks for taking a look so quickly Laurel!
