### ISSUE TITLE
Allow hide the post excerpt at 'Post Details' in Content Options Section

### ISSUE THREAD

**Issue by eduardogoncalves** [Automattic/newspack-theme#1099]
**Is your feature request related to a problem? Please describe.**
There's no option to hide the post excerpt at 'Post Details' in Content Options Section.

If  `Your homepage displays` is set to `Your latest posts`, it will diplay a list of post with the post excerpt with no options to hide it.
![image](https://user-images.githubusercontent.com/4308648/94996628-cd610e80-0573-11eb-8229-970be6fd77e2.png)

**Describe the solution you'd like**
We are able to hide everything besides post excerpt:
-  Display date
-  Display categories
-  Display tags
-  Display author

**Describe alternatives you've considered**
I'm able to hide it from home page by using css, but an option in Content Options Section would help non-developers.
```css
.home .post .entry-content {
	display: none;
}
```
![image](https://user-images.githubusercontent.com/4308648/94996734-58420900-0574-11eb-9b41-652935100e9c.png)

**Additional context**
![image](https://user-images.githubusercontent.com/4308648/94996353-47909380-0572-11eb-9548-a8b21792acae.png)

**Comment by laurelfulford** [comment]
Thanks for filing this @eduardogoncalves!

I think, since the core of Newspack users don't really use the Blog Posts page, this hasn't really gotten any other requests, so I'm going to close it for now. 

(As an aside, Content Options also get confusing with the options available under Template Settings > Archive Settings. Content Options come from Jetpack -- and [don't include an option to hide the excerpt in the available settings](https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php#L193-L217). The archive template in the theme was honestly a bit too opinionated to make sense with them from the get go, and it's just gotten worse as the theme has had more options added).

For specific sites who'd like to hide the excerpts on the blog posts page, I would recommend using Custom CSS, like:

```
.blog .entry-content {
    display: none;
}
```

The same can be done for the Archive pages by navigating to Customizer > Template Settings > Archive Settings, unchecking 'Show excerpts for all posts' and unchecking 'Use a large, featured display for the latest post in the archives'.

Just let me know if you have any questions about the above!
