### ISSUE TITLE
How to hide post published Date

### ISSUE THREAD

**Issue by vinvitthal** [Automattic/newspack-theme#1247]
**Expected behavior**
How to Hide published date in WP posts? Please add 'Date Visible or Not visible' option in theme customisation. 

Old Published Date issue is related to SEO, Google ranking is based on the date for the page, Updated post date not showing in Google SERP.

**Comment by laurelfulford** [comment]
Hi @vinvitthal! 

If you're using Jetpack, there is an option to hide the date on posts under Customizer > Content Options. It's part of the Newspack theme's support for [Jetpack's Content Options](https://jetpack.com/support/content-options/).

If you're not using Jetpack, you can hide the date using the Additional CSS field in the Customizer - the following will hide the date on single posts, archives, and search results:

```
.entry-meta span.posted-on {
	display: none;
}
```

If the Newspack theme you're using stacks the author name and date on single posts, adding this bit of CSS as well will help vertically center the author name with the avatar, once the date is gone:

```
.entry-header .entry-meta {
	display: flex;
	align-items: center;
}
```

If you wanted to show only the updated date, there is an option in the theme for `Show "last updated" date on single posts`, under Customizer > Template Settings > Post Settings; by default, it will show both the original published date, and the updated date, prefaced by the label 'Updated'. If you only wanted to show the updated date in these cases, you could turn that on, and use the Additional CSS field to hide the original published date using this CSS:

```
.show-updated .entry-date.published,
.show-updated .updated-label {
	display: none;
}
```
I found a bug when looking into this issue: originally the updated date was always output in the theme's HTML, but hidden; when we added the option to show the updated date on single posts, this stopped working. I'm working on a fix for that now; once it's in place, you should also be able to use CSS to show the updated date everywhere with something like this:

```
.posted-on .updated:not(.published) {
	display: inherit;
}
```

...or hide the published date and only show the updated date, without the `Show "last updated" date on single posts` option turned on:

```
.entry-date.published:not(.updated) {
	display: none;
}
.posted-on .updated:not(.published) {
	display: inherit;
}
```

Since we do have an option in the Customizer to hide the date when Jetpack is enabled, and a few work arounds with Custom CSS to hide the date if you'd rather not use Jetpack, I'm going to close this issue. But if you have any questions about the above, please let me know!

**Comment by vinvitthal** [comment]
Thanks for your support

And *How to Hide Author Avatar image in post??*

**Comment by laurelfulford** [comment]
Hi @vinvitthal! There is an option to hide avatars on the site under WP Admin > Settings > Discussion -- though the setting originally was added to WordPress for the comments, it will also hide the author avatars in the bylines, in the author bios in the footer, and at the top of the author archive pages.
