### ISSUE TITLE
Disable thumbnail generation if Jetpack 'site accelerator' and 'Speed up image' is enabled

### ISSUE THREAD

**Issue by eduardogoncalves** [Automattic/newspack-theme#1262]
**Is your feature request related to a problem? Please describe.**
When Jetpack's 'site accelerator' and 'Speed up image' is enabled, the Newspack theme doesn't use theme's thumbnails.
![image](https://user-images.githubusercontent.com/4308648/109058732-bacdaa00-76b9-11eb-9a33-1f03d5505aa4.png)
![image](https://user-images.githubusercontent.com/4308648/109058372-4c88e780-76b9-11eb-948e-51ae4e4ffc3c.png)

**Describe the solution you'd like**
Can we disable thumbnail generation if theme detect that Jetpack's 'site accelerator' and 'Speed up image' is enabled?

**Comment by laurelfulford** [comment]
Hi @eduardogoncalves!

Since this option has to do with a Jetpack feature alone, and not something tied directly to the Newspack theme, I think it would make more sense to add this as a small plugin to your site. Jetpack does have a filter that will allow you to turn off this option -- there's some more information about that here: 

https://developer.jetpack.com/hooks/jetpack_photon_noresize_mode/

I'm going to close this, since it seems like more of a plugin-level option than something that should be theme-specific, but please let me know if you have any questions!
