### ISSUE TITLE
Missing lines in newspack-theme.pot

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1267]
The file newspack-theme.pot has no string for translation the label of updated date of post:

	`Updated`

**Comment by mmprep** [comment]
No, everything is related to newspack-blocks.pot.
And the specified lines are present in it.
Closed.

**Comment by laurelfulford** [comment]
Hi @mmprep! 

This is very well timed! We _just_ updated the POT file yesterday to [include this string](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/languages/newspack-theme.pot#L957-L959) - it will be available now if you're checking out the theme from GitHub and building it yourself, and will be available in the next theme release, coming out some time next week. 

I'm going to close this issue, since the string has been added, but just let me know if you have any questions!
