### ISSUE TITLE
Logo: Header and Footer Logo Issues

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1292]
Issue 1

`Appearance -- Customize -- Site Identity -- Logo
`
You can select logo and then crop image OR skip cropping.

`Appearance -- Customize -- Site Identity -- Footer Logo
`
You can select logo and then ONLY crop image. Why you cannot just skip cropping?

Issue 2

I can't select the .svg image for the Footer Logo.
First, I can only crop the image (Issue 1). Second, if I try to crop the .svg image along its edges (not actually crop it), I get an error:

`	There has been an error cropping your image.
`

Issue 3

Increasing the size of the logo with the slider appears as a decreasing. And vice versa.
Perhaps I am the only one with the problem and it is not common?

See video attachment.

https://user-images.githubusercontent.com/61176171/110249816-1c7af780-7f89-11eb-8417-2843c2b1e804.mp4

**Comment by laurelfulford** [comment]
Hi @mmprep!

For item one: the Logo and Footer logo use two slightly different controls - the Logo uses the Custom Logo one, built into WordPress. The Footer Logo uses a more standard ['image uploader' control](https://developer.wordpress.org/reference/classes/wp_customize_cropped_image_control/) that's also available in WordPress, but not 1:1 with how the Logo works: the 'Skip Cropping' behaviour is a bit different. I normally work around it by just increasing the size of the crop area to fit my whole image, but it's still technically cropping it -- it's not the same as a full skip like with the regular logo.

I did some testing, and I think I have a work around for the SVGs, though -- the Footer Logo will show a 'Skip Cropping' button if your original SVG is smaller overall than the recommended size (400px x 300px). So if you can scale down your SVG to be less than 400px wide and less than 300px tall, it should let you skip the cropping. If the SVG can't be edited for whatever reason, you can also try editing this limit when you're first uploading the image -- the two values can be found in the /newspack-theme/inc/customizer.php [here](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/customizer.php#L354-L355). If you change them to values larger than your image just for the time it takes to upload, it should let you skip cropping, then return them to normal. 

For item three, this is a known issue (https://github.com/Automattic/newspack-theme/issues/610), but it doesn't crop up very often -- it seems to mostly affect wider, shorter logos. 

It's annoying, but thankfully it's only an issue with the Customizer preview -- the front-end should still reflect the direction you've moved the slider. When I've run into it, I've relied a bit on previewing the changes outside of the Customizer to make sure the logo was sized the way I wanted before saving. 

I'm going to close this issue since there's a work around for the first part (skipping cropping for the Footer logo), and an existing issue for the second part (the backwards logo resizer preview), but please let me know if you have any questions about the above!
