### ISSUE TITLE
Feature request: Link the author name in the bio

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#1336]
A publisher has asked that the author's name that appears at the end of the article (code ref below) is linked to their author archive page.

Additionally, the suggestion is that this is linked _instead of_ the "More by [Author]" link that appears below the bio.

Some questions this raises:

1. If we got rid of the "More by" link, would that be the default?
2. We would provide an option to include that or be prescriptive?
3. How would that impact sites who expect the "More by" link to be there?
4. Do we think linking the author name is obvious enough from a usability PoV?

https://github.com/Automattic/newspack-theme/blob/270a5fe8767fc7a66d3f6732574d1ad9634df9af/newspack-theme/template-parts/post/author-bio.php#L49

**Comment by laurelfulford** [comment]
I'm personally leery about changing the current behaviour and removing the 'More By' text all together, especially since it guides visitors to the full author bios on the archive pages if a site has it set up to be truncated.

We could link the author name as well, and the 'More by' text should be hideable via CSS for any specific publisher who wanted to do that, without impacting all publishers or adding too many theme options.

**Comment by laurelfulford** [comment]
Since this hasn't come up again, I'm going to close this request; if it does come back, we can link the new issue to this, or just reopen this one!
