### ISSUE TITLE
The Ability to conditionally set template

### ISSUE THREAD

**Issue by bfrye26** [Automattic/newspack-theme#1341]
Love how Newspack works and the speed it delivers this. But due to being a legacy site, moving over means setting different post styles individually. If there was a way to set different post styles based on conditions, it would help make the transition seemless. 

For example:

Post A (Category Movies) is automatically assigned the Full Width style
Post B (news) is assigned the small header style.

This simple conditioning would ensure sites can transition with as little grunt work as possible while taking advantage of features that are now in play. Also, would make it much easier to onboard new sites and outlets with as little stress as possible.

**Comment by laurelfulford** [comment]
Thanks for filing this issue, @bfrye26! Unfortunately, I think this is a bit beyond the scope of what we'd want to be building into the theme. 

When we've migrated existing sites, we've been handling setting templates or other bulk settings for existing posts by running scripts or queries through the database. Depending on the scale of the changes, you could even use the bulk editing options in WordPress to do things like changing the templates, and use the UI to sort posts by category. 

>  Post B (news) is assigned the small header style.

Just for clarity, it's not possible to change the site header on a per-post basis at this time. It might be something we can accomplish down the road using WordPress's full side editing, though! 

I'm going to close this issue just due to its scope, but please let me know if you have any questions!
