### ISSUE TITLE
Enable custom templates in WordPress 5.8

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-theme#1447]
WordPress 5.8's ability to create custom templates need to be enabled in the theme:

```
add_theme_support( 'block-templates' );
```

https://make.wordpress.org/core/2021/06/16/introducing-the-template-editor-in-wordpress-5-8/

I've tested this code on one of my non-Newspack sites and confirmed that it adds the desired functionality. Without it, the "New" link in this screenshot is missing:

![template-editor](https://user-images.githubusercontent.com/12199101/127225568-51e5b08d-028f-469f-b739-b656635ce5e0.jpg)

**Comment by laurelfulford** [comment]
@gamebits and I discussed this; the problem that needed to be solved was a publisher needing the ability to create block patterns, not templates, which unfortunately is not available through the Gutenberg/WordPress UI yet, so we can't opt-in at a theme level. 

I'm going to close this issue for now since we won't be adding standalone `add_theme_support( 'block-templates' );` to this theme exactly; we're looking into fully refreshing the theme with FSE capabilities, but modifying this one to do that -- without causing issues with sites using it -- is going to be a bit of a mess!

**Comment by uptimizt** [comment]
@laurelfulford can you clarify this issue?

- approximate timeline for the release of a new theme?
- will migration be easier or will it be necessary to start over?

**Comment by laurelfulford** [comment]
Hi @uptimizt! There isn't really any more information to offer at this time -- we're just starting to look into it! I just wanted offer some context around why we wouldn't be opting into full site editing options to this theme.
