### ISSUE TITLE
Legacy widget title classes getting changed when nested in a Group block

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1470]
When you nest a legacy widget inside of a group block, the widget title's class changes from `.widget-title` to `.widgettitle`.

Edited to add: it also looks like it's stripping out the `.accent-header` class that [the theme adds to the sidebar widgets](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/functions.php#L292).

This has already been reported in [the Gutenberg repo](https://github.com/WordPress/gutenberg/issues/33507), but to avoid visual issues in the short-term, I think we should 'duplicate' the `.widget-title` styles so they're also applied to this alternative class; it can be removed once this is fixed in WordPress.

**Comment by hawkeye126** [comment]
@laurelfulford I've added a fix for this issue here:

https://github.com/Automattic/newspack-theme/pull/1532

Steps to replicate:
1) Using default WordPress and News Pack Theme (any child theme)
2) Add a widget group
3) Add two legacy widgets of type meta
4) Add widget titles
5) On front end you will see the `.widget-title` and `.accent-header` classes are missing

Before:
![Screen Shot 2021-09-30 at 6 06 00 PM](https://user-images.githubusercontent.com/1033613/135550338-497f1575-a858-4ac9-8ced-e7469a58c90b.png)

After:
![Screen Shot 2021-09-30 at 6 05 38 PM](https://user-images.githubusercontent.com/1033613/135550356-7b1ecf06-e507-47d7-a03f-8a3c7ff08056.png)
