### ISSUE TITLE
Extra white space when using adsense ads

### ISSUE THREAD

**Issue by hhugosz** [Automattic/newspack-theme#1509]
**Describe the bug**
Responsive adsense ads result in extra white space on mobile devices.

**To Reproduce**
1. Go to https://comeananas.news/

**Screenshots**
![image](https://user-images.githubusercontent.com/69354831/132664890-8673acd3-c492-4e74-bf0f-ebf7f6e66bbc.png)

**Comment by laurelfulford** [comment]
Hi @hhugosz! This looks like it might be an issue with the ad itself -- if you inspect it, it has a width of 100vw on smaller screens, which means it will take up all of the space, from right to left of the screen. This is different than it taking up 100% of the _available_ space -- it's wider than the content area of the theme at this screen size. The ad space is sitting 5% away from the left side, but then pushing well past the right side, with the ad art centred in the middle of that:

![Screen Shot 2021-09-09 at 3 50 10 PM](https://user-images.githubusercontent.com/177561/132772773-3ee1095c-9423-41f6-b320-f9b7120fd6b3.png)

I can't say for certain without knowing how the ads have been set up (and I am far from an ads expert!), but changing the width of those mobile ads to 100% instead of 100vw should help, as it'll make the ad space fill the _available_ space, not be the whole screen width. 

Otherwise, you could use some custom CSS on smaller screens to "pull" the ad further to the left; it would be the same width, but it should at least appear centered. Something like this could be a good starting point, though it may need further tweaking depending on how ads have been set up throughout the site:

```
@media (max-width: 599px) {
    amp-ad[style*='width: 100vw'] {
        left: -5%;
    }
}
```

I'm going to close this issue, since it's not specifically related to the theme, but please let me know if you have any questions about the above!
