### ISSUE TITLE
Newspack Ads Supresion for members

### ISSUE THREAD

**Issue by mrsurfhunter** [Automattic/newspack-theme#1648]
Hello, 
We use the Newspack solution on one of our news websites orademedias.ro and I like it because of its simplicity, and also prepare the launch for a bigger news website. 
The newspack ads plugin is a great and easy solution for Google Ad Manager, however, in our case, it would be excellent to have in the suppression tab the option to hide ads not only by tags or archive, but for members - a hook to hide the ads to logged-in users.
Those who contribute as members with small monthly donations can enjoy the option to read the news without ads.
Thank you.

**Comment by kmwilkerson** [comment]
@mrsurfhunter Thank you for your suggestion! While we understand this is a capability that publishers would like to employ, it requires constant communication with a CRM tool, since this purpose would lead to users being required to be logged in across their devices (and we'd need to ask the CRM if the user is an _active_ donor prior to every ad call). Because CRMs varying widely from publisher to publisher, building a solution that would work across them all is not part of our product roadmap. 

Additionally, Newspack is an opinionated platform that believes this particular strategy is not in the best interest of most publishers, as revenue diversity is essential. It’s common across the industry for about 80% of revenue to come from 10 -20% of readers. That means simply that subscriber/members drive by far the highest proportion of revenue. Loyal readers generate the most page views and thus the most impressions. If you have a decent direct-sold strategy, your most engaged local advertisers are also going to want to reach your most engaged readers and have access to the largest pool of impressions.
