### ISSUE TITLE
Getting the author avatar when viewing a co-author profile

### ISSUE THREAD

**Issue by kariae** [Automattic/newspack-theme#1680]
**Describe the bug**
When Co-Authors Pro plugin is used, we get the author avatar from the Guest author post, which is the way to go, but when the guest author is linked to a WP User we should take the avatar of the WP User instead. This will unify the avatar of the user across the site, and fix the issue when we migrate authors by creating co-authors (without avatars) which will show an empty avatar in the author page even if the linked account has an avatar.

**To Reproduce**
1. Make sure to have GAP, and Simple Local Avatars (Used in some publishers sites to set local avatars for the authors) plugins installed.
2. Create a new guest author and link it to an existing user (the linked user should have an avatar, we can have this using Simple Local Avatars).
3. Go to the guest author public page and notice the avatar is not loaded.

**Expected behavior**
We should see the avatar of the linked user.

**Comment by laurelfulford** [comment]
Hi @kariae! This is actually the correct behaviour for the Co-Authors Plus plugin, but it's definitely confusing! If you map a Guest Author to a real user, you're basically "replacing" that real user's information on the front-end with the Guest Author's information -- avatar, name, biological write up, everything. 

There's a small mention of this [on the plugin's page](https://en-ca.wordpress.org/plugins/co-authors-plus), buried in the caption of the third slide of the slideshow: 

> You can also override existing WordPress account meta by mapping a guest author to a WordPress user. 

If something isn't populated on the Guest Author side (like their avatar, or biological information) rather than falling back to information from the existing user, it just doesn't show up -- it treats the Guest Author as the authoritative spot to draw all user information from. 

I remember having a lengthy dive into this on one of our sites before realizing what was happening 😖 It's not quite what I expected either! I'm going to close this issue, but please let me know if you have any questions or would like to discuss further!
