### ISSUE TITLE
Invalid script: amp-plus.js

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-theme#1732]
AMP validation is removing /themes/newspack-theme/js/dist/amp-plus.js from AMP pages. Isn't amp-plus.js required for newspack related features on AMP pages?

**Comment by laurelfulford** [comment]
Hi @yogeshbeniwal!

> Isn't amp-plus.js required for newspack related features on AMP pages?

That file is only needed on sites using the sticky sidebar ad placement, and it's enqueued when you have `define( 'NEWSPACK_AMP_PLUS_ENABLED', 'true' );` set in wp-config.php. 

You may have that flag set for another reason, like [to use the 'Stripe on-side checkout' option for the Donate Block](https://newspack.pub/support/blocks/donate-block/#stripe). So if you're not using the sidebar sticky ad at all, it's safe to leave the script as 'Removed'; if you are using it, marking the script as 'Kept' should fix. 

I'm going to close this issue, but just let me know if you have any questions about the above!

**Comment by yogeshbeniwal** [comment]
Thanks @laurelfulford. My understanding was that while using define( 'NEWSPACK_AMP_PLUS_ENABLED', 'true' ); it makes newspack required scripts automatically available in amp format using amp_validation_error_sanitized filters.

**Comment by laurelfulford** [comment]
@yogeshbeniwal I did a quick test on a brand new site to check that (since I wasn't 100% sure either way!). Steps were:

1. Create a new WordPress site.
2. Install the Newspack plugin and run the Wizard to install the themes, etc. 
3. Add the `define( 'NEWSPACK_AMP_PLUS_ENABLED', true );` flag to the wp-config.php file.

When I did that, the amp-plus.js file was marked as 'Kept' by default:

![image](https://user-images.githubusercontent.com/177561/160665603-b79d17be-2efc-4b78-9289-a0c6aba70d6d.png)

... but you can still switch them to 'Removed' -- so it does seem to keep them automatically, but you can also still override it (which could be helpful, going back to the ads example -- this file is only required when you are using sticky ads; if you aren't, you may want to remove it even though you have the `define( 'NEWSPACK_AMP_PLUS_ENABLED', true );` flag enabled for something else!

**Comment by yogeshbeniwal** [comment]
Thank you @laurelfulford for doing that. I did test it with localwp installation too but couldn't get it marked as kept automatically.

Wondering is this because i am using transitional mode rather than standalone mode or I must be doing something very wrong in wp-config.php, Screenshot below.

![Screen Shot](https://user-images.githubusercontent.com/7325107/160881081-c39ce00b-59ec-441b-a9d7-5966c2604b20.png)

Another instance where it should automatically mark as kept.

![Screen Shot](https://user-images.githubusercontent.com/7325107/160881602-9266d52d-b5d4-4dd4-b111-8f49b699f354.png)

**Comment by laurelfulford** [comment]
> Wondering is this because i am using transitional mode rather than standalone mode or I must be doing something very wrong in wp-config.php

It does look like Transitional could be a factor, looking at [this check](https://github.com/Automattic/newspack-plugin/blob/e62c5ba0710017a4dd788954804545edb8d4383f/includes/class-amp-enhancements.php#L51-L55) in the Newspack Plugin repo. Can you try switching to Standard and see if it resolves the problem you're seeing?

If it doesn't, I think the best next step would be to create an issue in the Newspack Plugin repo, so we can make sure that code is functioning as expected in all cases! (I'm afraid I'm far from an expert in that functionality, but posting in that repo will help get the right eyes on things!).

**Comment by yogeshbeniwal** [comment]
Started a discussion at https://github.com/Automattic/newspack-plugin/discussions/1578 for further discussion.
