### ISSUE TITLE
Header Size: H2 and H3 are the same on mobile 

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1812]
### Issue  1

In the desktop view, the sizes of H1-H6 are adequately decreasing.

<img width="753" alt="header-size-01" src="https://user-images.githubusercontent.com/61176171/169656941-0e526dbd-7440-4409-a822-775b326a5ca7.png">

True, there are complaints about the size of H5 and H6, which turn out to be smaller (0.8em and 0.7em) than the default size of the body text (1em). And that really doesn't make sense, because the point of any header is to highlight further text.

I took a look at the AMA Manual of Style. Here are some excerpts that seemed adequate to me:

> 22.1. 
> body type: The type characteristics used for the main body text of a work.
> display type: Type that differs from the body type of the text of a printed work. Display type is used in titles, headings, and subheadings and is usually larger than the body type.
> subhead: A subordinate heading.

> 21.8
> The type size and weight create emphasis or continuity, as needed. Headings and subheadings create the outline within the text to frame the article.

> 2.8.2
> Headings reflect the progression of logic or the flow of thought in an article and thereby guide the reader. Headings also help break up the copy, making the article more approachable.

It's interesting to see the discussion about H1-H6 sizes here https://stackoverflow.com/questions/55696808/why-do-h5-and-h6-have-smaller-font-sizes-than-p-in-most-user-agent-default. There seems to be a common negligence in standards development that no one is paying attention to.

### Issue 2

There is an obvious bug in the mobile view: H2 and H3 sizes are the same.

<img width="699" alt="header-size-02" src="https://user-images.githubusercontent.com/61176171/169656981-8d0cbcb0-6cf5-4c46-955e-7958186498a2.png">

**Comment by laurelfulford** [comment]
Thanks for reporting this @mmprep!

> True, there are complaints about the size of H5 and H6, which turn out to be smaller (0.8em and 0.7em) than the default size of the body text (1em). And that really doesn't make sense, because the point of any header is to highlight further text.

This is actually the first report we've had of this. I think given how long the styles have been in place and unremarked on, I'd like to keep them as they are -- I'm always hesitant to make visual changes like this when they don't involve fixing bugs, since they could negatively impact someone using the theme who likes the styles as they are. Individual sites can definitely override these using Custom CSS, or if you're working from a fork of the theme, by changing the theme styles! 

> There is an obvious bug in the mobile view: H2 and H3 sizes are the same.

I do agree that this seem wrong! I'm going to mark the issue as a bug, and tweak the title to reflect this specific issue. Thanks!

**Comment by mmprep** [comment]
@[laurelfulford](https://github.com/laurelfulford), thank you for your reply.

I'm sure the primacy of the H5 and H6 size message is due to the fact that perhaps no one gets that deep into the subheadings. Mostly everyone is limited to H2 and H3.
