### ISSUE TITLE
Add PWA error template

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#357]
The theme needs a customized PWA error template, it needs to be helpful and fallback gracefully. 

So we need to figure out:
* What it should have; what would be really helpful
* How best to carry over the current site's customizations

**Comment by westonruter** [comment]
I just tried turning off my network connection and going to a subsequent page on elsoberano.org, and I saw this:

![image](https://user-images.githubusercontent.com/134745/67035165-fc197700-f0cd-11e9-917e-23c8b32a60b7.png)

This could rather display the theme's own design and custom offline content if it included an `offline.php` template.  This was done for the WCEU site last year, with the offline template including the conference schedule.

Since it is an AMP-first site it is simpler to implement this since there is no need to worry about ensuring theme scripts and stylesheets are added to the precache. 

Eventually, the offline template should include a list of the URLs that are available offline. See also:

* https://github.com/WordPress/wordcamp.org/issues/205
* https://github.com/xwp/pwa-wp/issues/211

**Comment by claudiulodro** [comment]
I have a (non-public) note about the `offline.php` template at https://github.com/Automattic/newspack-issues/issues/7. @westonruter my notes say that you may be working on a version of the offline template in the PWA plugin that lists the available offline pages the user can read. Is this still something you're planning on, and do you think it'll be sometime soon? If so, I think we'd definitely want to incorporate that feature into our own `offline.php` template.

**Comment by westonruter** [comment]
It's something that's been on my todo list for awhile, but I'm not going to get to it until after WCUS at the earliest. It may be December. In any case, incorporating that feature into any theme's existing `offline.php` template should be straightforward when it's available.
