### ISSUE TITLE
Add Camera Icon before Captions on images 

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#504]
I would love this feature.

**Comment by laurelfulford** [comment]
Since we haven't had additional requests for this specific customization, I'm going to close this issue - it's a pretty opinionated visual choice, and I would recommend against adding it now since it would affect live sites in a way they may not want.

For a work-around, an icon could be added to specific sites using Custom CSS and the `:before` pseudo element -- something like this, but it would need to be updated to match the size/shape of the icon being used, and the path to where it's been uploaded to the Media Library:

```
figcaption::before,
.wp-caption-text::before {
    background-image: url('path/to/camera-icon.png');
    content: ' ';
    display: inline-block;
    margin-right: 0.25em;
    height: 1em;
    width: 1em;
}
```
