### ISSUE TITLE
Style 5: Colours aren't applied as expected

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#530]
**Describe the bug**

While using Style 5 I've set new primary and secondary colours but I still see the Newspack Blue being used:

**To Reproduce**
1. Open the customiser
2. Set Style 5
3. Go into colours and set a custom primary and secondary colour (I'm using `#202944` and `#6cc4e8`)
4. The section titles used in the Homepage Articles Block use the Newspack blue (`#36f`) instead of the custom colours.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/136342/67677545-37446180-f97c-11e9-8bdf-00e052dbb825.png)

**Expected behavior**
The colours chosen in the customiser should be used over the Newspack blue.

**Comment by laurelfulford** [comment]
Thanks for reporting this, Phil!

Unfortunately, this has to do with how style packs are previewed -- the 'default' style pack is always there, so you see some things from it all the time (like grey borders under those section titles, and its default of using the blue for that text). In this case, since Style 5 doesn't use the colours for that text, it doesn't have anything to override the default styles.

Although it doesn't sound anything like this issue, the underlying problem is the same as #174; because of that I'm going to close this issue.
