### ISSUE TITLE
More sharing button for amp version

### ISSUE THREAD

**Issue by iamjamilkhan** [Automattic/newspack-theme#571]
Theme is fast and stable now but still one feature annoying me. If we use theme without amp jetpack sharing button appear but with amp version in post only two share button available Facebook and Twitter. I would like if you add or show me way to get more button such WhatsApp, telegram and Facebook messenger it will help to get more engagement.

Actually I don't have any solution for this just want it to available. Also sharing button should be moved to below article so our audience can share after reading . No one share article without reading it. I find jetpack solutions to move sharing button below but didn't want to mess with code

**Describe alternatives you've considered**
You can add support an alternative sharing pulgin such as addthis or similar to this they also supports sticky sharing button at bottom side but not sure how will perform wit pwa pop up

**Additional context**
Hofe its enough to understand mine issue

**Comment by laurelfulford** [comment]
Hi @iamjamilkhan! 

The theme currently uses Jetpack for the sharing buttons. It sounds like a couple of your requests will need to be addressed with that plugin:

So far, only some of the sharing buttons are AMP compatible -- it looks like WhatsApp and Telegram are still waiting for support. [This Jetpack issue](https://github.com/Automattic/jetpack/issues/9730) has a table that lists outstanding functionality:  https://github.com/Automattic/jetpack/issues/9730#issuecomment-467683259 Outside of Facebook and Twitter, Linkedin, Tumblr and Pinterest should also work with AMP at this time.

The Jetpack Share buttons do not yet include Facebook Messenger, but there's a feature request for that here: https://github.com/Automattic/jetpack/issues/13948 

I tested the [AddThis sharing button plugin](https://wordpress.org/plugins/addthis/) with the theme. When you pick the 'sticky' sharing buttons, it displays well with no edits to the theme. It also supports Telegram and WhatsApp when AMP is enabled. When using an offline PWA version of a site, the sticky buttons still appear but the links don't work; this matches with how the Jetpack share buttons work in that situation. 

We do have an issue for the theme for exploring adding more sharing locations: #95 

Since parts of this issue will need to be resolved in Jetpack, and we have an existing issue for adding more sharing options to the theme, I'm going to close this ticket. Please let me know if you have any questions about the above; if anything is missing from #95 for what you're looking for, please add a comment there. Thanks!
