### ISSUE TITLE
Add Update date option in the article

### ISSUE THREAD

**Issue by techengage** [Automattic/newspack-theme#598]
An enhancement is requested.

Add Last updated option for posts and also the option to hide published date and only display updated date.

It will be of great use for news sites.

**Comment by laurelfulford** [comment]
The updated date has been added in https://github.com/Automattic/newspack-theme/pull/1154; since we haven't had additional requests to hide the original date, I'm going to close this issue -- it should be possible to do that on a per-site basis with the following CSS:

```
.entry-header .entry-date.published:not(.updated) {
    display: none;
}

.entry-header .entry-meta .updated-label {
    margin-left: 0;
}
```

If you don't want to display the "Updated" text in the above case, you could replace the `margin-left: 0` in that style with `display: none` as well.
