### ISSUE TITLE
Regarding Using Atomic Blocks with Newspack

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#603]
In the #GFWP meet, it was recommended to use Newspack plugin & theme plus the atomic blocks plugins for extra blocks. I tried atomic blocks for the homepage and it doesn't provide any option to control font size nor they were as good as the one built by Newspack. But the main issue I want to highlight here is since I am on full AMP (for mobile & Desktop both), using atomic blocks costs a lot on the CSS part. It takes a good amount of CSS being added for it and since CSS size is limited in AMP, I want to save as much as I can, hence I uninstalled the plugin. 

So, this is feedback & request, if the newspack can provide more blocks natively, it'll be a great help in staying full AMP for different kind of content & post types. 

Thanks

**Comment by laurelfulford** [comment]
Thanks for filing this issue, @akkiverma! 

Since it is related to blocks, rather than the theme, I've copied it over to here: https://github.com/Automattic/newspack-blocks/issues/254

If there's any additional information you can add -- like specific blocks you're interested in -- please comment on the issue there. Thanks!
