### ISSUE TITLE
Truncate author bios?

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-theme#607]
**Is your feature request related to a problem? Please describe.**

We've received a request to truncate the author bio on single posts when necessary to a reasonable length (~150 chars).

**Describe the solution you'd like**

We could use whatever the limit is for post excerpts or we could use a hard-coded limit. The feature probably makes sense to have automatically applied on all sites, with the full bio available on the author archive page.

**Describe alternatives you've considered**

Maybe a separate plugin for filtering the author bio limit or having a specific setting for truncating the author bio? I don't think this change will be controversial enough to warrant something like that, though.

**Comment by laurelfulford** [comment]
I think this is a handy addition!

Since we're adding it to live sites, I think having some kind of length control would be good, since it is an easy 'escape hatch' from this setting if someone doesn't want it. There's already a Author Bio Settings section in the Customizer -- I think it might make sense to go there, since the author bio code is already a big intense, with the Co-Authors Plus support.

I'll put together a PR and get some feedback on whether that approach makes sense!
