### ISSUE TITLE
Option for Adding Custom Code in Header, Body & Footer

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#620]
Hi,
It'll be great and very useful if there would be options to add custom codes (shortcodes & PHP) in the customizer at the following locations:

- After `<head>`
- Before `</head>`
- After `<body>`
- Before `</body>`
- Before `</footer>`

And moreover, I am confused if Newspack theme supports shortcodes or not? If those can be supported, it'll be helpful in many scenarios.

**Comment by laurelfulford** [comment]
Hi @akkiverma!

> It'll be great and very useful if there would be options to add custom codes (shortcodes & PHP) in the customizer at the following locations:

To be honest, this is unlikely something that we'll be adding to the theme, since it's something that many plugins do (searching for "code in header footer' [turned up a few](https://wordpress.org/plugins/search/code+in+header+footer/) in the WordPress plugins repo).

> I am confused if Newspack theme supports shortcodes or not? If those can be supported, it'll be helpful in many scenarios.

The Newspack theme doesn't include its own shortcodes, but should support any standard WordPress shortcodes (either using the Shortcode block, or adding them to the Classic Editor block). Are there specific ones that you're having issues with?

**Comment by akkiverma** [comment]
Yes I know I can insert using a plugin but most of them support Header and Footer only and not Inside Body. But it's still a very basic feature which most of the themes provide. For inserting in the body using Ad Injector, I've to manually add the PHP code in the theme files. That's why I created this thread.

**Comment by laurelfulford** [comment]
Ah, I see -- thanks for the additional information! 

Newspack does support inserting ads in other places, but it is handled in the Newspack Plugin (https://github.com/automattic/newspack-plugin), the Newspack Ads plugin (https://github.com/automattic/newspack-ads), and the [Super Cool Ad Insertor](https://wordpress.org/plugins/super-cool-ad-inserter/) plugin. It supports WordAds and Google Adsense.

I'm not familiar with Ad Injector, and a Google search didn't leave me confident that I had found the correct tool, but hopefully the above can help achieve what you're looking for! Any additional ad support will likely be added/handled by one of these solutions, rather than the theme itself.

**Comment by akkiverma** [comment]
My bad for Typo, it's Ad-Inserter (https://wordpress.org/plugins/ad-inserter/). It works perfectly with AMP. Also provides the option to add codes to header & footer as well.  I tried Newspack-Ads plugin; it had one issue that the ads being inserted by the plugin were all left-aligned. 

Didn't faced ads-alignment issue with Ad-Inserter. Also, Ad-Inserter provides a finer control on adding advertisements and custom codes. But it doesn't provide the option to add codes in `<body>`. 
So far to add auto-ads code in `<body>`, it's being taken care of by Adsense linkage via site-kit plugin automatically. Still, then I thought if theme also provides these option, it would come handy for many, nothing else.

**Comment by laurelfulford** [comment]
Ah thanks! 

>  I tried Newspack-Ads plugin; it had one issue that the ads being inserted by the plugin were all left-aligned.

This sounds like a bug! I created an issue for that here: https://github.com/Automattic/newspack-ads/issues/12

> Also, Ad-Inserter provides a finer control on adding advertisements and custom codes.

We're definitely open to adding features to the Newspack Ads functionality -- if you can provide some specifics about exactly what controls would be helpful, or the kind of custom code that you need to use, please let us know [here](https://github.com/automattic/newspack-ads), and we can look into it! 

I am going to close this issue, but only because the ad code for Newspack isn't handled in the theme. If you have any questions about what I've written above, though, please comment here!
