### ISSUE TITLE
Post template: Change Default?

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#624]
Not sure what would be required here, but it would be very handy if it were possible to change the default template used by new posts and pages.

Right now you can manually change between a few options, but if a site wanted to always use, say, the one column centred option, it would make it a lot easier to always start with that and have the option to switch, rather than having to change it 9 times out of 10. 

Ideally this could be handled in a similar way to the Featured Images (an option in the customizer?) so it wouldn't affect posts/pages that already had the template changed.

**Comment by laurelfulford** [comment]
This has come up again here; it would be a handy thing to include in the theme if possible: https://github.com/Automattic/newspack-theme/issues/675

**Comment by philipjohn** [comment]
It's come up again :) Some thoughts popped into my head about how we might do it. The customiser option sounds good for actually setting the default.

On individual posts, if the default template is selected the `_wp_page_template` post meta is blank/non-exitstent so the first thing we'd need to do is make sure that is _explicitly_ set so that changing the default doesn't changed previously saved posts. We could do that by hooking the post save action.

Next, we'd need to filter WP's list of templates, and it would make sense to show each of the templates, named, with an indication of which is the default. Example:

![Screenshot from 2020-05-06 10-12-48](https://user-images.githubusercontent.com/136342/81160694-4be46080-8f82-11ea-81c5-c8373d235e5d.png)

We'd need to make clear in the customizer option that changing that will only affect _future_ posts and won't retrospectively change the template for any post that was already saved.

I can definitely see folks wanting a separate default for posts vs pages, too, so we should consider that at the same time.

**Comment by jeffersonrabb** [comment]
Another request for this from @sonjaleix, for Cityside.
