### ISSUE TITLE
Remove Post Permalink from Date

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#627]
Hi,

I was wondering why the date in metadata is linked to Post permalink. It's linked everywhere whether its single post or archive. It can be quiet bad for SEO. You can tell me a way to disable this?

To tackle this, for now, I've linked the post title to post URL by modifying theme file directly, but hoping if something like this can be implemented in future versions and removed permalinks from date. 

```
<h1 class="entry-title">
		<a href="<?php the_permalink(); ?>" rel="bookmark">
			<?php echo wp_kses_post( get_the_title() ); ?>
		</a>
	</h1>
```

**Comment by laurelfulford** [comment]
Hi @akkiverma! Unfortunately, there isn't a way to disable the link (outside of editing the code, as you have). The post dates include permalinks to help in the odd case where a post might not have a title (so there's still a way to link to the post). 

However, they shouldn't be linked on single posts, since it doesn't really do anything. Thanks for the heads up about that!

**Comment by akkiverma** [comment]
Thank you
