### ISSUE TITLE
Showing metadata like a sentence

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#628]
Hi, 

In Post metadata everywhere shows "By Author" some space "Date".

Why not rather make it "By Author on Date".

I modified theme file code to make it show link a sentence on single posts - https://www.reviewcenter.in/9767/vivo-v17-with-quad-rear-cameras-launched/

Just modified the code to 

```
<div class="entry-meta">
			<?php newspack_posted_by(); ?> on <?php newspack_posted_on(); ?> 
		</div><!-- .meta-info -->
```

Added appropriate CSS for proper spacing and it looks great. I was hoping if you liked this idea, it can be implemented natively in the theme everywhere whether its single posts or the archives or loop?

**Comment by laurelfulford** [comment]
Hi @akkiverma!

Depending on the style pack or individual post settings, sometimes the date and author don't sit on the same line together -- this is why there isn't any text connecting them, like 'on'. For example, Style 2 looks like:

![image](https://user-images.githubusercontent.com/177561/70559624-e5c2f100-1b3b-11ea-8901-2a5a276df81b.png)

Since the theme is on live sites already, I'm leery about changing it as it may be unwanted in some cases. I'm going to close this issue because of that, but I appreciate you making the suggestion!
