### ISSUE TITLE
Reduce Pullquote Font Size

### ISSUE THREAD

**Issue by 4waam** [Automattic/newspack-theme#687]
I would like to reduce the font size of the Pullquote. The page where I recently used it. 
https://4wheelsandamotor.com/general/farmers-are-turning-back-the-technology-clock/

I would like the font size to be similar to the heading text size. I don't want to lose the pullquote cite functionality or any of the other layout parts to it.

**Comment by laurelfulford** [comment]
Hi @4waam!

Unfortunately, we can't fully change the size of the block in the theme, as it's already used on some live sites, and changing it would change it on sites that may not want that update.

There are a couple other options, though:

1. Have you tried the 'Quote' block instead of the 'Pullquote' block? It is the same size as the regular body type, and unbolded (making it easier to read for longer text). It also includes a citation:

![image](https://user-images.githubusercontent.com/177561/72460328-72874d00-3781-11ea-895a-02bf73b8a343.png)

2. You can adjust the size of the block on your site by using the Additional CSS field in the Customizer. Something like this would reduce the font size:

```
.wp-block-pullquote blockquote p {
	font-size: 1.3em;
}
```

You can make that number a bit higher or lower to adjust the font size to where you'd like it to be. The only downside with this option is that the updated size won't be reflected in the editor.

I'm going to close this issue, but please comment here if you have any questions at all about the above!

**Comment by 4waam** [comment]
Thank you. This is what I was looking for. Sorry it seemed like I wanted a theme change!

**Comment by laurelfulford** [comment]
No worries! 😄 I'm glad that did the trick!
