### ISSUE TITLE
Style 2 (Nelson): Header overlap not working on homepage when title visible

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#711]
Came up in the review of #704: if you have a static homepage set, but do not have the homepage title hidden, the header overlap doesn't work:

![image](https://user-images.githubusercontent.com/177561/72743677-f914a380-3b60-11ea-919e-08321b2fd0d5.png)

The page should still display with the overlap, even if the title is visible.

**Comment by douglasferraz89** [comment]
Hi @laurelfulford , this bug is since last year.

The problem is that newspack-theme inserts the following css code.

`/* Static Front Page. */
.newspack-front-page.hide-homepage-title .entry-header {
  display: none;
}

.newspack-front-page .site-content {
  margin-top: 0;
}

@media only screen and (min-width: 782px) {
  .newspack-front-page .site-content {
    margin-top: 0.5rem;
  }
}

.newspack-front-page .entry-footer {
  margin-bottom: 0;
}`

And Newspack Nelson needs to modify the site-content margin-top.

The following code does this...

`.site-content,
.newspack-front-page.hide-homepage-title .site-content,
.site-breadcrumb {
	@include media( tablet ) {
		margin-top: #{-3.5 * $size__spacing-unit};
	}

	@include media( desktop ) {
		margin-top: #{-6 * $size__spacing-unit};
	}
}`

However it does not work on the static front page.

It is necessary to modify for this.

`.site-content,
.newspack-front-page. .site-content,
.site-breadcrumb {
	@include media( tablet ) {
		margin-top: #{-3.5 * $size__spacing-unit};
	}

	@include media( desktop ) {
		margin-top: #{-6 * $size__spacing-unit};
	}
}`

I fix this in my custom css.

`@media only screen and (min-width: 782px) {
  .site-content,
  .newspack-front-page .site-content {
    margin-top: -3.5rem;
  }
}

@media only screen and (min-width: 1168px) {
  .site-content,
  .newspack-front-page .site-content {
    margin-top: -6rem;
  }
}`

**Comment by laurelfulford** [comment]
Closing in favour of the newer duplicate #1020, just to tidy up old issues!
