### ISSUE TITLE
MailChimp Widget: Improve appearance

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#729]
![image](https://user-images.githubusercontent.com/177561/73029387-48223900-3dec-11ea-96bd-76da5dfe8105.png)

Ideally the form fields would fill the space better, and have vertical spacing, and the 'Sign Up' button would be on its own line.

**Comment by adekbadek** [comment]
I'm assuming this is about Jetpack's Mailchimp block – might be wrong though since it looks differently, but two years have passed :D 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/7383192/151590555-cbd902aa-1ab8-4b6b-9d49-1b3513279acc.png">

It looks good!

Closing, but feel free to open if the assumption is incorrect.

**Comment by laurelfulford** [comment]
@adekbadek It's been so long that I can't say either way if it was the block or not! 😆 

It was either that or the MC4WP plugin, but I know now that plugin's appearance depends so much on the markup you've set up in the plugin, it's not really something we can fix at the theme level!
