### ISSUE TITLE
Unable to hide date, category, author in Single Post or Archives

### ISSUE THREAD

**Issue by ashishmohta** [Automattic/newspack-theme#749]
**Describe the bug**
When customizing the theme, under Content options > Post Details, we can check or uncheck to display/ hide date, categories, etc.

It is not working even if I save it. However, it does hide when you are customizing, but not in reality. I had to comment on the PHP file to do it.

**To Reproduce**

You can see it here https://www.technospot.in/category/indionline/ but not here https://www.technospot.in/know-your-electoral-details-by-sending-sms/

**Comment by ashishmohta** [comment]
Anybody else seeing this?

**Comment by laurelfulford** [comment]
I can't recreate the issue with the date -- in my testing, it does hide in all cases. I do see some issues, though:

In some cases, the author avatar isn't hidden for me when hiding the author on single posts: 

![image](https://user-images.githubusercontent.com/177561/74258966-ff072b80-4cab-11ea-8af1-f9112c651917.png)

There is also some unwanted cruft when hiding some things -- for example, this bar when hiding only the date:

![image](https://user-images.githubusercontent.com/177561/74258584-6d97b980-4cab-11ea-83e2-6ba789855507.png)

There might be a couple other issues, depending on the settings, that will need some more testing when this is being worked on. 

@ashishmohta I'm not sure if this is lining up with what you're seeing, since you've hidden the date/categories in another way. But if there's another issue you're seeing, can you please add a screenshot? Thanks!

**Comment by ashishmohta** [comment]
What I did: 

Disable options which display date, author, etc from the Theme customization  It didn't work. So I went ahead and commented on the code level.

![Screenshot 2020-02-11 at 10 38 51 PM](https://user-images.githubusercontent.com/2024142/74260176-12071380-4d1f-11ea-8fe4-55a1b3bb1c91.png)

![Screenshot 2020-02-11 at 10 29 45 PM](https://user-images.githubusercontent.com/2024142/74259700-53e38a00-4d1e-11ea-8f9a-8431e4eb1ce6.png)

I haven't commented on code level for Archive Page though. So you can see even though the option is disabled in the Theme customizer, it still displays them.

![Screenshot 2020-02-11 at 10 32 03 PM](https://user-images.githubusercontent.com/2024142/74260058-ea17b000-4d1e-11ea-94d1-000a49e9cdcf.png)






 I have commented Author and date on Single Post Pages.
