### ISSUE TITLE
Please Bring Night Mode or so called Dark Mode to the Theme 🌃

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#777]
Hi Automattic and Newspack Team Members,

This is Sanjay suggesting you guys a feature called **Dark Mode** to include in the theme as most of the websites nowadays include the same. The feature could be accessible via a **toggle option** to turn it ON and OFF or may be at the advanced level the feature could use the respective **timezone** to automatically get turned ON and OFF. You know what I mean.

If Newspack able to bring the same option, then it would became the first native AMP framework to include such feature.

Hope you guys consider my recommendation.

With Sincere Regards,
Sanjay

**Comment by laurelfulford** [comment]
Thanks for filing this issue @SanjayKumarMonu!

Unfortunately, with the different colour option in the theme and blocks, and trying to handle the contrast there, it's very complex to add this to the theme at this time. Because of that, I'm going to close this issue, but please let me know if you have any questions!
