### ISSUE TITLE
What is meant by CI Infrastructure Improvement?

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#810]
Hi Newspack Team,

First and the Foremost, I would like to congratulate you for building such an awesome them.

Well, Recently, Newspack Theme Alpha 33 released with CI Infrastructure Improvement.

Could you guys please enlighten us about the same feature i.e. CI Infrastructure Improvement.

Regards,
Sanjay

**Comment by laurelfulford** [comment]
Hi @SanjayKumarMonu!

The Newspack theme (and plugins) use CircleCI -- Continuous Integration -- to help us with code formatting, bundling releases, and other part of our development workflow. Any commits to the theme or plugins that refer to 'CI' are about adding and improving that tooling, and not features are are otherwise available in the theme/plugins.

Hope that helps! There's some more information about CircleCI on their site if you're interested:  https://circleci.com/
