### ISSUE TITLE
AMP Validation Errors using Newspack

### ISSUE THREAD

**Issue by panchammsinghh** [Automattic/newspack-theme#822]
I am testing the Newspack theme and plugin on my site. And everything is fine, especially the speed is amazing, But when i'm using the theme alongside the AMP official plugin (in standard mode) which is both for desktop and mobile. Then, It will show a bunch of AMP validation errors. As, I am a newbie, i don't know how to solve those errors, please help me in solving these errors.

Here's the screenshot - 
![image](https://user-images.githubusercontent.com/61957280/76181502-53d48e00-61e7-11ea-958e-af71eb51434c.png)

It show error with famous plugins like Wordfence Security, Table of Content plus, and PWA.

Waiting for a response.

**Comment by laurelfulford** [comment]
Hi @panchammsinghh,

As part of it simplifying and speeding up webpages, AMP will strip out JavaScript, and display these errors to warn you that it has done that. In some cases, it won't cause any issues -- for example, WordPress's core functionality should still work as expected, and Newspack and any of its recommended plugins should work with or without AMP enabled (even when they display errors)> 

For third-party plugins, it depends whether or not the plugin can function without JavaScript, or whether it has been made AMP-compatible by the plugin developers. If you're trying to use a plugin that does not work when AMP is enabled, you could reach out to the plugin developer and submit a feature request to add support. 

If it's a plugin that, say, embeds something on one or two posts, you could also turn off "Enable AMP" on those specific posts/pages using the options in the right sidebar: 

![image](https://user-images.githubusercontent.com/177561/85475802-8bcfc900-b56b-11ea-9de8-4c5730e324a7.png)

I'm going to close this issue because it's not specifically related to Newspack, but AMP and AMP-compatible plugins; hopefully this helps point you in the right direction!
