### ISSUE TITLE
Header: Add option for sticky header

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#84]
Make a 'sticky' navigation available in the theme; could use the 'shorter' menu designs mocked up in styles D and E, and used for the feature articles for style B and C. 

Example: https://www.propublica.org/

**Comment by laurelfulford** [comment]
We've had another request for this functionality from @akkiverma in #621:

> **Is your feature request related to a problem? Please describe.**
> Sometimes the blog posts are quite long and since AMP doesn't have JUMP to TOP button, it can be sometimes very frustrating scrolling back to the top.
> 
> **Describe the solution you'd like**
> I've checked code and the amount of CSS required for adding just JUMP to TOP button, hence rather I think it is better to provide an option for enabling sticky header on both desktop and mobile so that it becomes easier for users to navigate to other pages. 
> 
> **Describe alternatives you've considered**
> There is none so far.
> 
> **Additional context**
> I am hoping if sticky header can also have a search button along with the menu button when on mobile.

**Comment by AktharAZIF** [comment]
Hey, just wanted to know if you guys are still planning to do this since this feature request has been opened for more than a year and it's still not added with the theme.

**Comment by eduardogoncalves** [comment]
@laurelfulford and if it it was 'smart sticky', like https://www.saibatudomt.com.br/
As Newspack uses AMP, this is easy to implement, just add `amp-fx="float-in-top"` to container

```html
<header id="page-header" amp-fx="float-in-top">
      <div on="tap:header-sidebar.toggle" role="button" tabindex="0" class="navbar-trigger" title="Exibir o Menu" aria-label="Menu">
        <amp-img width="24px" height="24px" layout="fixed" src="https://www.saibatudomt.com.br/wp-content/themes/saibatudo2019/img/twotone-menu-24px.svg" alt="" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:24px;height:24px;" i-amphtml-layout="fixed">
      </amp-img></div>

      <div class="logo">
        <a href="/" data-rel="prefetch">
        <amp-img width="124px" height="48px" layout="fixed" src="https://www.saibatudomt.com.br/wp-content/themes/saibatudo2019/img/SaibaTudoMT.svg" alt="SaibaTudoMT" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:124px;height:48px;" i-amphtml-layout="fixed">
      </amp-img></a>
      </div>

      <div on="tap:search-sidebar.toggle" role="button" tabindex="0" class="navbar-trigger">
        <amp-img width="24px" height="24px" layout="fixed" src="https://www.saibatudomt.com.br/wp-content/themes/saibatudo2019/img/twotone-search-24px.svg" alt="Busca" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:24px;height:24px;" i-amphtml-layout="fixed">
      </amp-img></div>
    </header>
```

**Comment by laurelfulford** [comment]
Apologies! I ended up creating a second issue for this, which is just splitting the information (#826).

We do still plan on adding this -- thanks for your exploration @eduardogoncalves! One issue I ran into with `float-in-top` is the required `overflow: hidden` -- it means that menus with dropdowns ends up getting cut off. So we'll probably need to figure out a way to fit that in with the other header settings that we offer.

I copied over some other details from #826 from myself and @thomasguillot, and will close the newer issue:

> The main potential issue is height: the header's height, in part, depends on the size of the logo, so it can be variable. We will need to 'know' the height to set a proper sticky menu. This is usually done with JavaScript, but using AMP limits what's available there. So this will need digging into -- it may be possible to use the same scroll-position logic that's used in the popups, or we could set a fixed height for the headers with this setting -- overriding the custom logo size -- to ensure they're a consistent height.

> I would do this because:

> 1. We don't have to worry about JS. It can be done with CSS-only.
> 2. We avoid bad practice if a site has a massive fixed header that takes 50% of the screen height.

> I'd hoped to use AMP's [float-in-top](https://amp.dev/documentation/components/amp-fx-collection/#float-in-top,-float-in-bottom) effect for this (which has the header scroll away with the page, but appear again when you scroll back up), but it requires you to have `overflow: hidden` on the element, which means, for the header, that the menu dropdowns get cut off.

**Comment by AktharAZIF** [comment]
@laurelfulford 
Hi there,
This feature could be achieved by using amp-script along with amp-fx-collection. I see that you have already tried amp-fx-collection from your above comment. What you need to do is to add float-in-top in header tag and put the header tag inside amp-script tag. Since amp script is executed in worker dom after all the elements are rendered  we can then change the overflow:hidden to visible in '#masthead' using it . I tested this out and found that it will not affect the working of amp-fx-collection and the dropdown navigation will no longer get cut offs. The only problem with this method is that you need specify a fixed height since layout="container" would not work since the header tag is fixed which returns  '0' height. you can see an example of this at https://thewiretap.in/ (may not look clean in all screen size since i didn't add any media queries to the height attr)

**header.php**
`   <amp-script  width="100%" height="71px"  src="<?php echo get_bloginfo('template_url') . '/assets/js/amp-main.js?v=' . wp_get_theme()->get('Version'); ?>" >
<header amp-fx="float-in-top .... > </header>
</amp-script>`

**amp-main.js**
`document.getElementById("masthead").style.overflow = "visible";`

I used external script instead of inline script because official amp plugin runs into some issue while generating script hash

**Comment by AktharAZIF** [comment]
@laurelfulford 
I forgot i mentioned that website here and made it private for now for some reasons.sorry for that. But still i hope you got the idea on what was talking about.

**Comment by philipjohn** [comment]
Another request came in today from a publisher for this feature.
