### ISSUE TITLE
Selectively use Yoast's "primary category" feature

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#861]
**Is your feature request related to a problem? Please describe.**

The theme [currently uses](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/template-tags.php#L150-L160) the "Primary Category" as provided for by the Yoast SEO feature. The code comment says (my emphasis) "Only display Yoast primary category *if set*" but it's not possible to _not_ set a primary category:

![Screenshot from 2020-04-02 12-14-36](https://user-images.githubusercontent.com/136342/78243435-ac900180-74db-11ea-924e-18c83d40a437.png)

Some publishers use a well thought-through category structure and expect them all to show on a single article page, so it seems a little redundant to them for the theme to only print out one.

**Describe the solution you'd like**

A better solution may be to make the theme reflect the wording in the [code comment](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/template-tags.php#L150):

> Only display Yoast primary category if set.

This would probably require changing the category drop-down Yoast inserts to add a default option of "None" or similar.

**Describe alternatives you've considered**

An alternative could be that there's a more general theme setting, in the customiser, that tells the theme whether or not to use the "Primary Category" feature globally. This might result in the drop-down being hidden when disabled. I'd suggest that in this scenario the Primary category should be disabled by default, but open to opposing viewpoints.

**Additional context**

This came out of a specific request from a Newspack publisher.

**Comment by laurelfulford** [comment]
Riffing on this further, the single category is used both in the theme and the block.

If we use `add_filter( 'wpseo_primary_term_taxonomies', '__return_empty_array' );`, both would show a full list of categories. I think if we go with this route, it should be handled in a separate plugin, since it affects more than the theme.

If it's just an issue with the theme itself not showing all categories, then it would make sense to handle as a theme option; we could use it to override the [`newspack_categories()`](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/template-tags.php#L193-L226) function to also return the full list if enabled (since that's where the custom code lives to set it to show one or all categories depending if Yoast is enabled).

We could also approach the latter with a one off plugin, replacing the `newspack_categories()` function.

@philipjohn do you have a preference for approach here? Any of these options should be pretty straight forward to implement.
