### ISSUE TITLE
Google Pagespeed Insight Showing some Opportunities to Improve

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#956]
Hi Newspack Theme Wranglers,

This is Sanjay, Currently using the Newspack Theme on my website and I must say it is super awesome.

However, I would like point out an issue more specifically and improvement recommendation that I recently spot in the theme after Google rolls out the [Core Web Vitals](https://web.dev/vitals/).

I spot the issue while testing my website speed on Google Page Speed Insight. There it is showing (like as I show you in the screenshot below) the theme uses some unused Javascript that minutely degrades the website speed.

So, I wanna know, if there is some way to fix this. If so, then please let us know or if possible optimize the theme that way too. Let me again tell you, earlier it was not the case but now after the roll out of Core Web Vitals, these issues are appearing.

Regards,
Sanjay

![Remove Unused Javascript](https://user-images.githubusercontent.com/28781570/83329840-4c35fa00-a2a9-11ea-8f5f-f6bf683685d5.jpg)

**Comment by laurelfulford** [comment]
Hi @SanjayKumarMonu!

All of these scripts are coming from AMP; it looks like this issue has been reported in one of the AMP repos here: https://github.com/ampproject/amphtml/issues/28638

Since it doesn't seem to be specific to the theme I'm going to close this issue for now, but have subscribed to that issue in case there are updates there that indicate there is something we need to change here. If you have any questions at all, just let us know!
