### ISSUE TITLE
Bug: Jetpack social sharing icons cause display issues in Nelson theme post headers

### ISSUE THREAD

**Issue by sarahquigley** [Automattic/newspack-theme#965]
**Describe the issue**
Jetpack social sharing icons cause display issues in Newspack Nelson theme post headers/

**To Reproduce**
1. Go to Jetpack plugin
2. Turn on Social sharing
3. Visit one of your posts
4. See display issues in post header

**Screenshots**
An example of one of the broken post headers:
![Screenshot 2020-06-04 at 13 42 42](https://user-images.githubusercontent.com/1569881/83793067-00e56800-a66a-11ea-8fb4-fa264855f0f0.png)
It should look like this:
![Screenshot 2020-06-04 at 13 52 05](https://user-images.githubusercontent.com/1569881/83793481-984abb00-a66a-11ea-99fe-54a7f0a11d03.png)
These are my social sharing settings
![Screenshot 2020-06-04 at 13 43 53](https://user-images.githubusercontent.com/1569881/83793156-270b0800-a66a-11ea-8791-8e3cc3da917e.png)

**Expected behavior**
Social sharing should not break post header display.

**Comment by sarahquigley** [comment]
These display issues could exist on other themes. I haven't tested.

**Comment by laurelfulford** [comment]
Thanks for reporting this, @sarahquigley!

It's an issue with the Jetpack sharing buttons and AMP -- the AMP version of the buttons doesn't support some of the functionality, including the 'More' menu -- usually buttons that are not supported are just stripped out, but the 'More' menu causes some odd display issues. 

There is an issue for this in the Jetpack repo here: https://github.com/Automattic/jetpack/issues/12639

Removing the 'More' part of the social menu should fix the visual issues on the site for the short-term. 

I'm going to close this issue since it's related to Jetpack's AMP compatibility for the social share buttons, but if you have any questions about the above, just let me know!
