### ISSUE TITLE
Bug: Jetpack social sharing settings not respected by theme

### ISSUE THREAD

**Issue by sarahquigley** [Automattic/newspack-theme#966]
**Describe the bug**
The social sharing settings set within Jetpack are not reflected in how social sharing icons are displayed in the Newspack Nelson theme. (This issue may affect all themes, I haven't tested.)

**To Reproduce**
1. Turn on Jetpack social sharing
2. Configure it within Jetpack as preferred
3. Visit a post
4. Only Facebook and Twitter sharing icons display, independent of Jetpack settings

**Screenshots**
My chosen settings:
![Screenshot 2020-06-04 at 13 43 53](https://user-images.githubusercontent.com/1569881/83794109-7998f400-a66b-11ea-8299-8781fd748b46.png)
The icons I am seeing:
![Screenshot 2020-06-04 at 13 44 10](https://user-images.githubusercontent.com/1569881/83794120-8289c580-a66b-11ea-8b9e-ed0717e452b2.png)

**Expected behavior**
Social sharing icons displayed should reflect the settings chosen within Jetpack.

**Comment by laurelfulford** [comment]
Hi @sarahquigley!

The display of the buttons are coming from Jetpack's AMP compatible version of the buttons, which have one fixed appearance.

[Jetpack's GitHub repo](github.com/automattic/jetpack) is probably the best location to request enhancements for these buttons. It should also be possible make some visual changes with CSS -- something like the following should them closer to the rounded option you have picked:

```
.sd-content amp-social-share {
    background-size: 32px;
    border-radius: 100%;
    margin-right: 15px;
    max-height: 40px;
    max-width: 40px;
}
```

Unfortunately it won't be possible to replicate all the options this way, but hopefully this helps!

Since this issue is not related to the theme, I'm going to close this ticket but if you have any questions about the above, just let me know!
