### ISSUE TITLE
Newspack Katharine Too much space between headline and Youtube embed

### ISSUE THREAD

**Issue by deverman** [Automattic/newspack-theme#967]
**Describe the bug**

Using a Youtube embed on the Katharine theme results in a large space between the H2 and the embed.

https://www.nowshenzhen.com/news/new-wuhan-corona-virus-ncov-china/

**To Reproduce**
1. Using the Gutenburg editor create an h2 headline
2. Create an embed block below the headline
3. Embed a Youtube link
4. Save and preview and you will see a big space. 

**Screenshots**
Attached screen shot showing odd spacing

**Expected behavior**
Would expect a reasonable amount of space between the headline and the Youtube embed 
<img width="1620" alt="Screen Shot 2020-06-08 at 10 59 38" src="https://user-images.githubusercontent.com/802318/83988974-7c4f5e00-a977-11ea-888c-8329d7447836.png">

**Comment by laurelfulford** [comment]
Hi @deverman! This is an issue with AMP and recent updates in the Gutenberg plugin (8.2+). 

There is a fix in the works here: https://github.com/ampproject/amp-wp/issues/4810

In the meantime, you can prevent the extra space from turning off the "Resize for smaller devices" for each block -- AMP is already taking care of styles to make these embeds responsive, so this doesn't need to be turned on when AMP is enabled.

Since this is not theme-related, I'm going to close this issue, but if you have any questions just let us know!
