### ISSUE TITLE
Add support to upload webp to the function.php 

### ISSUE THREAD

**Issue by 4waam** [Automattic/newspack-theme#968]
I have to add this code to the function.php every time there is an update:

//** *Enable upload for webp image files.*/
function webp_upload_mimes($existing_mimes) {
    $existing_mimes['webp'] = 'image/webp';
    return $existing_mimes;
}
add_filter('mime_types', 'webp_upload_mimes');

//** * Enable preview / thumbnail for webp image files.*/
function webp_is_displayable($result, $path) {
    if ($result === false) {
        $displayable_image_types = array( IMAGETYPE_WEBP );
        $info = @getimagesize( $path );

        if (empty($info)) {
            $result = false;
        } elseif (!in_array($info[2], $displayable_image_types)) {
            $result = false;
        } else {
            $result = true;
        }
    }

    return $result;
}
add_filter('file_is_displayable_image', 'webp_is_displayable', 10, 2);

**Describe the solution you'd like**
Please add this code or similar to the theme function.php files in the parent and child themes so it is native.

**Describe alternatives you've considered**
I do this manually now. Not great for managing a site with multiple authors.

**Comment by laurelfulford** [comment]
Hi @4waam! I think a plugin would be a better approach for adding something like this -- that way, rather than the theme needing to include any possible mime type people may want to use, they can tailor their own sites with flexibility to meet their needs.

There are a couple plugins in the WordPress.org repository that look like they allow you to edit what mime types are available, or just enable webP:

* https://en-ca.wordpress.org/plugins/wp-add-mime-types/
* https://wordpress.org/plugins/wp-enable-webp/

... and I'm sure there are others, too! You could also create a simple plugin with the code you have above, if you prefer that approach. 

I'm going to close this issue, but if you have any questions about the above, please let me know!
