### ISSUE TITLE
Please Integrate any Web Push Notification 🔔 Service with the Theme

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#976]
Hi Newspack Theme Developers,

First and the Foremost, I would like to congratulate you guys for building such an awesome theme. However, there are some services if you integrate with the theme then that will engage more and more users to the website using this theme.

Yes I am talking about **Web Push Notification Service**. While requesting this feature, I already have tested some of the few Web Push Notification Service  available out there but none of them working perfectly well with the theme as you can see the theme sports native amp.

So, could you guys please add a web push notification service with the native version of the theme.

Regards,
Sanjay

**Comment by laurelfulford** [comment]
Thanks for submitting this issue @SanjayKumarMonu! 

Since we haven't had additional requests for this functionality, I'm going to close this issue. If it is something we tackle down the road, it will likely be as part of a separate plugin, since it doesn't have to be attached to the theme.

It looks like some Push Notification services -- like OneSignal -- do have steps to follow to use them on AMP-compatible pages: 

https://documentation.onesignal.com/docs/amp-web-push-setup
