### ISSUE TITLE
Donate Button On Mobile

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-theme#977]
**Is your feature request related to a problem? Please describe.**
The Donate button is generally placed in the Tertiary menu, which gets folded into the slide out menu on mobile. Because of the high business importance of the Donate button, best practice is to have the button immediately visible on mobile as shown in the screenshot below.

Additionally, it might be nice to have a separate color control for the donate button. Best practice suggests that Donate button should be a color outside of
 the site's palette, so that it stands out clearly. 

h/t @tristanloper for these suggestions.

**Describe the solution you'd like**
One possible approach would be to pull the Donate button out of the menus entirely. Instead call it something like "Primary CTA", and allow setting the URL/Color/Text. 

**Additional context**
![image](https://user-images.githubusercontent.com/1477002/84920938-d21bb880-b091-11ea-8e1f-35c514d8db7b.png)

**Comment by laurelfulford** [comment]
> One possible approach would be to pull the Donate button out of the menus entirely. Instead call it something like "Primary CTA", and allow setting the URL/Color/Text.

This could be a good approach, because some sites don't really use the Tertiary menu for CTAs like Donate buttons -- for example, Technode uses it more as a way to split the main menu into two: 

![image](https://user-images.githubusercontent.com/177561/85315353-c5230e80-b46f-11ea-8fff-dcb4baa5c429.png)

We could still use the same colour options for the 'menu-highlight' class (the way we're currently making the Donate button stand out). We have a  few sites that use Custom CSS to do something similar (to make it pop beyond what the theme does), so this would be a much nicer way for publications to customize it.

**Comment by laurelfulford** [comment]
Amendment to the original request -- this button should also show up in cases where the rest of the menu isn't visible, like the simple subpage header -- example:

![image](https://user-images.githubusercontent.com/177561/85877610-42aa8f80-b78c-11ea-8b61-be2d00b4f518.png)
