### ISSUE TITLE
AMP is not validating

### ISSUE THREAD

**Issue by courtneybl** [Automattic/newspack-theme#980]
**Describe the bug**
Despite being an "AMP accessible" theme, Newspack Sacha is creating "CSS overload" according to Wordpress after tree-shaking from the AMP plugin. Though I suspect some of it may be from WP itself, is there anyone knowledgeable on how to fix this issue?

The error code for the Sacha + Newspack issues are "STYLESHEET_TOO_LONG" relating to the custom colors and fonts.

**Screenshots**
![image](https://user-images.githubusercontent.com/67172855/85206143-e825b500-b2ed-11ea-939c-f71cf8dd0462.png)
![image](https://user-images.githubusercontent.com/67172855/85206152-f5db3a80-b2ed-11ea-9ead-0f978ad78463.png)
![image](https://user-images.githubusercontent.com/67172855/85206158-fd9adf00-b2ed-11ea-95c7-8e924dc7caa4.png)

**Expected behavior**
AMP accessibility, after all, that is what the theme advertises!

**Comment by laurelfulford** [comment]
Hi @courtneybl!

The Newspack theme supports AMP, but it doesn't guarantee AMP validation, since that can include a lot of other factors, like other plugins that are installed. 

We haven't had issues with excessive CSS with a Newspack site since AMP increased the limit for CSS in version 1.4.4 of the plugin -- that might be a good thing to check first, to make sure the plugin is up-to-date. 

In my testing, out of the box, Newspack Sacha + Custom Colours and Custom Fonts and the standard Newspack plugins used 55% of the available CSS:

![image](https://user-images.githubusercontent.com/177561/85322704-9ca11180-b47b-11ea-8145-8422bc5df4a7.png)

Other things that may be contributing to excessive CSS are other plugins you have installed, or any Custom CSS added to a site. Prior to the CSS limit being increased in AMP, we did run into issues with pages or posts with a _lot_ of different Gutenberg blocks added to them -- I think it would need to be very extreme with the new CSS limit, but many different blocks with different settings can add a fair bit of CSS, between the Gutenberg plugin and the theme. 

Hopefully the above helps troubleshoot this issue on your site!

**Comment by courtneybl** [comment]
Do you suggest removing the Gutenberg plugin then? I'd assume that means I have to go back and revamp all my posts.

**Comment by laurelfulford** [comment]
> Do you suggest removing the Gutenberg plugin then...?

Not at all! It's just the only case I've run into the warning with Newspack sites, but not since the AMP plugin increased the CSS limit, and we did some simplification of the CSS on our end. So first, can you confirm that the AMP plugin on your site is up to date?

Next, what kind of content is on the posts that are over the CSS capacity? Is it just the default suite of Gutenberg blocks, or ones being loaded by other plugins other than the Newspack Blocks plugin? Are there a lot of different blocks with different settings in these posts? (Some blocks include inline styles, so even if you have multiple versions of the same block, they could be loading additional CSS on a per-block basis to change their appearance).

Are there any other plugins that would be adding CSS that's loaded on these single posts?

**Comment by courtneybl** [comment]
I've deactivated the Gutenberg plugin for now, to see if that'll fix future posts...we'll see if things change with future articles.

> So first, can you confirm that the AMP plugin on your site is up to date?

The AMP for Wordpress plugin is up to date-- it is on 1.5.3. I was wondering if I should use "standard" as AMP suggests, but whenever I tried to turn on Standard, it messed up the entire theme. Examples below.

Everything shifts over to the left + gets resized strangely (before + after):
![image](https://user-images.githubusercontent.com/67172855/85338879-1b647180-b4b1-11ea-9f49-d2bbf6a9d6fd.png)
![image](https://user-images.githubusercontent.com/67172855/85338824-038ced80-b4b1-11ea-9c34-6cd4fc94f38b.png)

Or gets totally destroyed like the homepage (before + after):
![image](https://user-images.githubusercontent.com/67172855/85338710-caed1400-b4b0-11ea-84f3-ec0b3fa79f4e.png)
![image](https://user-images.githubusercontent.com/67172855/85338655-b3159000-b4b0-11ea-8206-cae11e12f2e3.png)

> what kind of content is on the posts that are over the CSS capacity?

They are articles with photos.
I think all of our posts aren't being AMP validated, which led me to suspect it was Gutenberg. However, you mentioned that I shouldn't need to remove it... so I have no idea what's wrong. We also use some other widgets (star ratings) and there's bolding/italics/hyperlinks...but I would imagine AMP would be okay with such "tiny" things? (Maybe they're a lot larger/denser for code than I assume they are). I hope I'm not breaking any rules by linking the site, but you can see some examples for yourself [here](https://discussingfilm.net/2020/06/18/7500-review-joseph-gordon-levitt-is-in-top-form-in-this-brilliant-thriller/) and [here](https://discussingfilm.net/2020/02/08/the-2020-oscars-where-to-watch-all-the-nominated-films/).

> Are there any other plugins that would be adding CSS that's loaded on these single posts?

I don't think so. I haven't introduced Newspack to my team yet (since we just switched over fairly recently), but before we just used the block/Gutenberg editor.
Besides that, the only plugins we have are the Newspack plugin, Akismet, Jetpack, Redirection (which isn't even on posts as far as I know), Site Kit, CoBlocks (which we don't use), Full Site Editing, Yoast SEO, Layout Grid, Page Optimize, and Smush. Most of the plugins were pre-installed when we updated to the Business plan.

My sincerest apologies for asking so many questions! It's such a lovely theme that you and your team have developed, and I want to use it!

**Comment by laurelfulford** [comment]
Thanks @courtneybl -- those links are a big help!

I did a bit of digging and I think I narrowed this down to two issues:

**Posts shifting and looking weird**: This is a known issue related to the Share buttons -- the AMP version of the buttons, when you use the 'More' section, or sometimes the default buttons styles, causes some invalid markup on the page. Usually this presents as a couple of odd bullet points, but the Newspack theme's HTML is structured in such a way that it blows things up (as you've seen!). 

Removing the 'More' section from the social share links should help -- there's a related issue in the Jetpack repo here: 

https://github.com/Automattic/jetpack/issues/12639

AMP doesn't fully support the share buttons as they work in Jetpack -- as mentioned, the 'More' section does not work, and some of the buttons may be stripped out. 

**CSS Limits**: On your site, it looks like this is also related to Jetpack, specifically the [Toolbar Notifications](https://jetpack.com/support/notifications/) -- it loads a CSS file that includes an icon font encoded as base64 ([example of the file](https://s0.wp.com/i/noticons/noticons.css)). Normally AMP will remove any CSS that's not used on a page, but it loads most of this file every time because it doesn't know all of that font code isn't needed, and that eats up about 1/3 of your available CSS. Turning off the Notifications should help - you can do this by navigating to /wp-admin, and going to Jetpack > Dashboard, scrolling to the very bottom and clicking 'Modules':

![image](https://user-images.githubusercontent.com/177561/85469389-730ee580-b562-11ea-845c-7f0fe0d76b18.png)

... then finding Notifications in the list, and clicking 'Deactivate' next to it:

![image](https://user-images.githubusercontent.com/177561/85469444-84f08880-b562-11ea-92f2-562a968d67ae.png)

That should free up a decent amount of CSS -- it's still possible to hit limits, but it should take more than just some paragraphs and images!

Just let me know if you have any questions about the above, and if this does the trick for you.

**Comment by courtneybl** [comment]
Thank you so much! It worked perfectly. That was so tricky. Your help is greatly appreciated.
I don't know if I should be the one to close this thread, so I will leave it open for you to do so.

**Comment by laurelfulford** [comment]
Awesome! Thanks for confirming that did it! :)
